# Generated by Django 2.0.5 on 2018-06-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('codechef', models.CharField(max_length=25)),
                ('spoj', models.CharField(max_length=25)),
                ('codeforce', models.CharField(max_length=25)),
                ('last_sync', models.DateTimeField(null=True)),
            ],
        ),
    ]
