# Generated by Django 2.0.5 on 2018-06-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_sync',
            field=models.DateField(blank=True, null=True),
        ),
    ]
