# Generated by Django 2.0.5 on 2018-06-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180620_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codechef',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='codeforce',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='spoj',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
