# Generated by Django 2.0.6 on 2018-06-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sj',
            name='submission',
        ),
    ]
