# Generated by Django 2.0.6 on 2018-06-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_cc_cf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codechef',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='codeforce',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='spoj',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
