# Generated by Django 2.0.6 on 2018-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180627_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totalCC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='totalCF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='totalSJ',
            field=models.IntegerField(default=0),
        ),
    ]
