# Generated by Django 2.0.6 on 2018-07-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180627_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='cc',
            name='problem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cf',
            name='problem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sj',
            name='problem',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
