# Generated by Django 2.0.6 on 2018-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180717_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codechef',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='codeforce',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='spoj',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
